import AppKit
import SwiftUI
import UniformTypeIdentifiers

extension Prefs {
    static let clipboardLimit = PrefKey("clipboard.limit", 50)
    static let clipboardCaptureImages = PrefKey("clipboard.captureImages", true)
    /// Bundle ids whose copies are never recorded (comma separated). Defaults to common password managers.
    static let clipboardExcludedApps = PrefKey("clipboard.excludedApps", [
        "com.1password.1password", "com.agilebits.onepassword7", "com.agilebits.onepassword-osx",
        "com.bitwarden.desktop", "com.lastpass.LastPass", "com.dashlane.dashlanephonefinal",
        "org.keepassxc.keepassxc", "in.sinew.Enpass-Desktop", "com.apple.keychainaccess", "com.apple.Passwords",
    ].joinedIDs)
}

struct ClipItem: Identifiable, Codable, Equatable {
    enum Kind: String, Codable { case text, link, image }

    let id: UUID
    var kind: Kind
    var text: String?
    /// File name of the saved image inside the clipboard folder.
    var imageFile: String?
    var date: Date
    var pinned: Bool
    var sourceApp: String?
}

/// Recent text, links and images copied to the clipboard. Stored only on this Mac.
@Observable
@MainActor
final class ClipboardModule: NotchModule {
    let id = "clipboard"
    let name = "Clipboard"
    let icon = "doc.on.clipboard"
    /// Off until the user turns it on: clipboard history is privacy-sensitive.
    var enabledByDefault: Bool { false }

    private(set) var items: [ClipItem] = []
    /// Item most recently copied back (for the "Copied" checkmark).
    private(set) var lastCopiedID: UUID?

    @ObservationIgnored private var watcher: PasteboardWatcher?
    private static let fileName = "clipboard.json"

    /// Pasteboard markers apps use for passwords and one-off data (nspasteboard.org).
    private static let skippedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "de.petermaurer.TransientPasteboardType",
    ]

    static var imagesFolder: URL {
        let dir = JSONStore.directory.appendingPathComponent("Clipboard", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }

    init() {
        items = JSONStore.load([ClipItem].self, from: Self.fileName) ?? []
    }

    // MARK: Lifecycle

    func setActive(_ active: Bool) {
        if active {
            if watcher == nil {
                watcher = PasteboardWatcher { pasteboard in
                    AppState.shared.module(ClipboardModule.self)?.capture(pasteboard)
                }
            }
            watcher?.start()
        } else {
            watcher?.stop()
        }
    }

    // MARK: Capturing

    private func capture(_ pasteboard: NSPasteboard) {
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.skippedTypes) else { return }
        let source = NSWorkspace.shared.frontmostApplication
        if let bundleID = source?.bundleIdentifier, Prefs.clipboardExcludedApps.value.idList.contains(bundleID) { return }
        let sourceName = source?.localizedName

        if let string = pasteboard.string(forType: .string), !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            let isLink = !trimmed.contains(where: \.isWhitespace)
                && (URL(string: trimmed)?.scheme.map { ["http", "https"].contains($0.lowercased()) } ?? false)
            insert(ClipItem(id: UUID(), kind: isLink ? .link : .text, text: String(string.prefix(20_000)),
                            imageFile: nil, date: .now, pinned: false, sourceApp: sourceName))
        } else if Prefs.clipboardCaptureImages.value,
                  let image = NSImage(pasteboard: pasteboard),
                  let tiff = image.tiffRepresentation,
                  let png = NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:]),
                  png.count < 15_000_000 {
            let id = UUID()
            let file = "\(id.uuidString).png"
            do {
                try png.write(to: Self.imagesFolder.appendingPathComponent(file), options: .atomic)
                insert(ClipItem(id: id, kind: .image, text: nil, imageFile: file, date: .now, pinned: false, sourceApp: sourceName))
            } catch {
                // Skip images we can't store.
            }
        }
    }

    private func insert(_ item: ClipItem) {
        if let text = item.text, let existing = items.firstIndex(where: { $0.text == text }) {
            // Same text copied again: move it to the top (keeping its pin).
            var moved = items.remove(at: existing)
            moved.date = .now
            moved.sourceApp = item.sourceApp ?? moved.sourceApp
            items.insert(moved, at: 0)
        } else {
            items.insert(item, at: 0)
        }
        trim()
        save()
    }

    private func trim() {
        let limit = max(5, Prefs.clipboardLimit.value)
        var unpinnedSeen = 0
        var kept: [ClipItem] = []
        for item in items {
            if item.pinned {
                kept.append(item)
            } else if unpinnedSeen < limit {
                unpinnedSeen += 1
                kept.append(item)
            } else {
                deleteFile(of: item)
            }
        }
        items = kept
    }

    // MARK: Actions

    func copy(_ item: ClipItem) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        switch item.kind {
        case .text, .link:
            pasteboard.setString(item.text ?? "", forType: .string)
        case .image:
            if let image = image(for: item) { pasteboard.writeObjects([image]) }
        }
        watcher?.ignoreCurrentContents()
        lastCopiedID = item.id
        // Bump it to the top like a fresh copy.
        if let index = items.firstIndex(where: { $0.id == item.id }) {
            var moved = items.remove(at: index)
            moved.date = .now
            items.insert(moved, at: 0)
            save()
        }
    }

    func togglePin(_ item: ClipItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].pinned.toggle()
        trim()
        save()
    }

    func remove(_ item: ClipItem) {
        deleteFile(of: item)
        items.removeAll { $0.id == item.id }
        save()
    }

    /// Clears everything except pinned items.
    func clearHistory() {
        for item in items where !item.pinned { deleteFile(of: item) }
        items.removeAll { !$0.pinned }
        save()
    }

    func image(for item: ClipItem) -> NSImage? {
        guard let file = item.imageFile else { return nil }
        return NSImage(contentsOf: Self.imagesFolder.appendingPathComponent(file))
    }

    private func deleteFile(of item: ClipItem) {
        guard let file = item.imageFile else { return }
        try? FileManager.default.removeItem(at: Self.imagesFolder.appendingPathComponent(file))
    }

    private func save() {
        JSONStore.save(items, to: Self.fileName)
    }

    // MARK: Excluded apps

    func runAddExcludedAppPanel() {
        let panel = NSOpenPanel()
        panel.allowedContentTypes = [.application]
        panel.allowsMultipleSelection = true
        panel.directoryURL = URL(fileURLWithPath: "/Applications")
        panel.prompt = "Exclude"
        NSApp.activate(ignoringOtherApps: true)
        guard panel.runModal() == .OK else { return }
        var ids = Prefs.clipboardExcludedApps.value.idList
        for url in panel.urls {
            if let id = Bundle(url: url)?.bundleIdentifier, !ids.contains(id) { ids.append(id) }
        }
        Prefs.clipboardExcludedApps.set(ids.joinedIDs)
    }

    // MARK: NotchModule

    func compactView() -> AnyView { AnyView(ClipboardCompactView(module: self)) }
    func expandedView() -> AnyView { AnyView(ClipboardExpandedView(module: self)) }
    func settingsView() -> AnyView { AnyView(ClipboardSettingsView(module: self)) }
}
